parameters:

services:
  melodia_user.event.authentication_success_listener:
    class: Melodia\UserBundle\EventListener\AuthenticationSuccessListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
