Melodia\UserBundle\Entity\User:
    properties:
        username:
            - NotBlank:
                groups: [create, update]
            - Length:
                max: 255
                groups: [create, update]
        plainPassword:
            - NotBlank:
                groups: [create]
            - Length:
                max: 255
                groups: [create]
        fullName:
            - Length:
                max: 255
                groups: [create, update]
